# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://tzolkin.github.io
title: Tzolkin - Ruby on Rails Developer
email: fzavaladev@gmail.com
description: > # "Francisco Zavala its a Oaxaco developer, gamer 'de coraza!',
  mastodon fan and tasajo lover."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/fzavaladev
  - title: github
    url: https://github.com/tzolkin
  - title: linkedin
    url: http://mx.linkedin.com/pub/francisco-zavala/12/b62/a51/
